---
apiVersion: v1
kind: Service
metadata:
  name: yelb-ui
  labels:
    app: yelb-ui
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    # nodePort: 32777 <- if not specified, the system will generate a nodePort value
  selector:
    app: yelb-ui
    tier: frontend
